language: node_js
dist: trusty
node_js: 8.9
sudo: true

addons:
  google-chrome: latest

script:
  - xvfb-run npm test

after_script:
  - cat ./coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
